### ISSUE TITLE
MonetDBLite no longer on CRAN

### ISSUE THREAD

**Issue by Quantitative72** [bdetweiler/c-diff-and-renal-failure#1]
Do you have work around?

**Comment by bdetweiler** [comment]
This is the first I've heard of it, and that is unfortunate. Sounds like
Hannes Muehleisen is working on a new project called DuckDB. Not sure how
backwards compatible it will be, but this project used mostly basic CRUD
SQL features, so hopefully it will be easy to migrate.
See the discussion here: https://github.com/MonetDB/MonetDBLite-R/issues/38
